# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_postgisbbox.ui'
#
# Created: Fri Nov 25 20:50:39 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PostgisBBox(object):
    def setupUi(self, PostgisBBox):
        PostgisBBox.setObjectName(_fromUtf8("PostgisBBox"))
        PostgisBBox.resize(630, 684)
        PostgisBBox.setWindowTitle(QtGui.QApplication.translate("PostgisBBox", "PostgisBBox", None, QtGui.QApplication.UnicodeUTF8))
        PostgisBBox.setStyleSheet(_fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(PostgisBBox)
        self.buttonBox.setGeometry(QtCore.QRect(280, 650, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.ConnectToPostgis = QtGui.QPushButton(PostgisBBox)
        self.ConnectToPostgis.setEnabled(True)
        self.ConnectToPostgis.setGeometry(QtCore.QRect(530, 50, 81, 31))
        self.ConnectToPostgis.setText(QtGui.QApplication.translate("PostgisBBox", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnectToPostgis.setCheckable(False)
        self.ConnectToPostgis.setDefault(False)
        self.ConnectToPostgis.setObjectName(_fromUtf8("ConnectToPostgis"))
        self.layersLabel = QtGui.QLabel(PostgisBBox)
        self.layersLabel.setGeometry(QtCore.QRect(310, 100, 171, 21))
        self.layersLabel.setText(QtGui.QApplication.translate("PostgisBBox", "Postgis Tables (Layers)", None, QtGui.QApplication.UnicodeUTF8))
        self.layersLabel.setObjectName(_fromUtf8("layersLabel"))
        self.ConnessioniPostgis = QtGui.QComboBox(PostgisBBox)
        self.ConnessioniPostgis.setGeometry(QtCore.QRect(170, 50, 171, 31))
        self.ConnessioniPostgis.setEditable(False)
        self.ConnessioniPostgis.setObjectName(_fromUtf8("ConnessioniPostgis"))
        self.DatabaseConnectionsLabel = QtGui.QLabel(PostgisBBox)
        self.DatabaseConnectionsLabel.setGeometry(QtCore.QRect(160, 0, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DatabaseConnectionsLabel.setFont(font)
        self.DatabaseConnectionsLabel.setText(QtGui.QApplication.translate("PostgisBBox", "Connection to Postgis Database", None, QtGui.QApplication.UnicodeUTF8))
        self.DatabaseConnectionsLabel.setObjectName(_fromUtf8("DatabaseConnectionsLabel"))
        self.DatabaseLabel = QtGui.QLabel(PostgisBBox)
        self.DatabaseLabel.setGeometry(QtCore.QRect(20, 50, 111, 31))
        self.DatabaseLabel.setText(QtGui.QApplication.translate("PostgisBBox", "Select Database \n"
"Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.DatabaseLabel.setObjectName(_fromUtf8("DatabaseLabel"))
        self.tableWidget = QtGui.QTableWidget(PostgisBBox)
        self.tableWidget.setGeometry(QtCore.QRect(240, 130, 371, 141))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("PostgisBBox", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("PostgisBBox", "Schema", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("PostgisBBox", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.widget = QgsMapCanvas(PostgisBBox)
        self.widget.setGeometry(QtCore.QRect(240, 360, 371, 281))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.DatabaseConnectionsLabel_2 = QtGui.QLabel(PostgisBBox)
        self.DatabaseConnectionsLabel_2.setGeometry(QtCore.QRect(270, 280, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DatabaseConnectionsLabel_2.setFont(font)
        self.DatabaseConnectionsLabel_2.setStyleSheet(_fromUtf8("font: 10pt \"Ubuntu\";\n"
"font: 12pt \"Ubuntu\";"))
        self.DatabaseConnectionsLabel_2.setText(QtGui.QApplication.translate("PostgisBBox", "Select Bounding Box from Map", None, QtGui.QApplication.UnicodeUTF8))
        self.DatabaseConnectionsLabel_2.setObjectName(_fromUtf8("DatabaseConnectionsLabel_2"))
        self.SelectMapcomboBox = QtGui.QComboBox(PostgisBBox)
        self.SelectMapcomboBox.setGeometry(QtCore.QRect(240, 330, 181, 31))
        self.SelectMapcomboBox.setObjectName(_fromUtf8("SelectMapcomboBox"))
        self.SelectMapcomboBox.addItem(_fromUtf8(""))
        self.SelectMapcomboBox.setItemText(0, QtGui.QApplication.translate("PostgisBBox", "Google Street", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectMapcomboBox.addItem(_fromUtf8(""))
        self.SelectMapcomboBox.setItemText(1, QtGui.QApplication.translate("PostgisBBox", "Google Satellite", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectMapcomboBox.addItem(_fromUtf8(""))
        self.SelectMapcomboBox.setItemText(2, QtGui.QApplication.translate("PostgisBBox", "Google Physical", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectMapcomboBox.addItem(_fromUtf8(""))
        self.SelectMapcomboBox.setItemText(3, QtGui.QApplication.translate("PostgisBBox", "OpenStreetMap", None, QtGui.QApplication.UnicodeUTF8))
        self.ZoomIn = QtGui.QPushButton(PostgisBBox)
        self.ZoomIn.setGeometry(QtCore.QRect(520, 330, 31, 31))
        self.ZoomIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ZoomIn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ZoomIn.setAutoFillBackground(False)
        self.ZoomIn.setStyleSheet(_fromUtf8(""))
        self.ZoomIn.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PostgisBBox/zoomin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZoomIn.setIcon(icon)
        self.ZoomIn.setIconSize(QtCore.QSize(26, 26))
        self.ZoomIn.setCheckable(False)
        self.ZoomIn.setAutoDefault(True)
        self.ZoomIn.setObjectName(_fromUtf8("ZoomIn"))
        self.ZoomOut = QtGui.QPushButton(PostgisBBox)
        self.ZoomOut.setGeometry(QtCore.QRect(550, 330, 31, 31))
        self.ZoomOut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ZoomOut.setStyleSheet(_fromUtf8(""))
        self.ZoomOut.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PostgisBBox/zoomout.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZoomOut.setIcon(icon1)
        self.ZoomOut.setIconSize(QtCore.QSize(26, 26))
        self.ZoomOut.setObjectName(_fromUtf8("ZoomOut"))
        self.Pan = QtGui.QPushButton(PostgisBBox)
        self.Pan.setGeometry(QtCore.QRect(580, 330, 31, 31))
        self.Pan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pan.setStyleSheet(_fromUtf8("background-image: url(:/plugins/PostgisBBox/pan.png);"))
        self.Pan.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PostgisBBox/pan_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Pan.setIcon(icon2)
        self.Pan.setIconSize(QtCore.QSize(32, 32))
        self.Pan.setObjectName(_fromUtf8("Pan"))
        self.SearchEdit = QtGui.QLineEdit(PostgisBBox)
        self.SearchEdit.setGeometry(QtCore.QRect(10, 340, 151, 31))
        self.SearchEdit.setText(_fromUtf8(""))
        self.SearchEdit.setObjectName(_fromUtf8("SearchEdit"))
        self.SearchButton = QtGui.QPushButton(PostgisBBox)
        self.SearchButton.setGeometry(QtCore.QRect(170, 340, 51, 31))
        self.SearchButton.setStyleSheet(_fromUtf8("font: 9pt \"Ubuntu\";"))
        self.SearchButton.setText(QtGui.QApplication.translate("PostgisBBox", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchButton.setObjectName(_fromUtf8("SearchButton"))
        self.tableSearch = QtGui.QTableWidget(PostgisBBox)
        self.tableSearch.setGeometry(QtCore.QRect(10, 420, 211, 221))
        self.tableSearch.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableSearch.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableSearch.setShowGrid(False)
        self.tableSearch.setObjectName(_fromUtf8("tableSearch"))
        self.tableSearch.setColumnCount(2)
        self.tableSearch.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("PostgisBBox", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.tableSearch.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("PostgisBBox", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.tableSearch.setHorizontalHeaderItem(1, item)
        self.goMap = QtGui.QPushButton(PostgisBBox)
        self.goMap.setGeometry(QtCore.QRect(170, 390, 51, 21))
        self.goMap.setText(QtGui.QApplication.translate("PostgisBBox", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.goMap.setObjectName(_fromUtf8("goMap"))
        self.layersLabel_3 = QtGui.QLabel(PostgisBBox)
        self.layersLabel_3.setGeometry(QtCore.QRect(10, 390, 101, 21))
        self.layersLabel_3.setText(QtGui.QApplication.translate("PostgisBBox", "Search Results", None, QtGui.QApplication.UnicodeUTF8))
        self.layersLabel_3.setObjectName(_fromUtf8("layersLabel_3"))
        self.DatabaseLabel_2 = QtGui.QLabel(PostgisBBox)
        self.DatabaseLabel_2.setGeometry(QtCore.QRect(110, 120, 111, 31))
        self.DatabaseLabel_2.setText(QtGui.QApplication.translate("PostgisBBox", "Filter by:", None, QtGui.QApplication.UnicodeUTF8))
        self.DatabaseLabel_2.setObjectName(_fromUtf8("DatabaseLabel_2"))
        self.comboBoxschema = QtGui.QComboBox(PostgisBBox)
        self.comboBoxschema.setGeometry(QtCore.QRect(110, 180, 111, 27))
        self.comboBoxschema.setObjectName(_fromUtf8("comboBoxschema"))
        self.DatabaseLabel_3 = QtGui.QLabel(PostgisBBox)
        self.DatabaseLabel_3.setGeometry(QtCore.QRect(110, 150, 111, 31))
        self.DatabaseLabel_3.setText(QtGui.QApplication.translate("PostgisBBox", "schema", None, QtGui.QApplication.UnicodeUTF8))
        self.DatabaseLabel_3.setObjectName(_fromUtf8("DatabaseLabel_3"))
        self.layersLabel_2 = QtGui.QLabel(PostgisBBox)
        self.layersLabel_2.setGeometry(QtCore.QRect(10, 320, 161, 21))
        self.layersLabel_2.setText(QtGui.QApplication.translate("PostgisBBox", "Insert city (es. Rome)", None, QtGui.QApplication.UnicodeUTF8))
        self.layersLabel_2.setObjectName(_fromUtf8("layersLabel_2"))

        self.retranslateUi(PostgisBBox)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PostgisBBox.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PostgisBBox.reject)
        QtCore.QMetaObject.connectSlotsByName(PostgisBBox)

    def retranslateUi(self, PostgisBBox):
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item = self.tableWidget.horizontalHeaderItem(1)
        item = self.tableWidget.horizontalHeaderItem(2)
        self.tableSearch.setSortingEnabled(True)
        item = self.tableSearch.horizontalHeaderItem(0)
        item = self.tableSearch.horizontalHeaderItem(1)

from qgis.gui import QgsMapCanvas
import zoom_in_rc
import pan_rc
import zoom_out_rc
